apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          env:
            - name: FOO1
              value: bar1
            - name: FOO2
              value: bar2
            - name: FOO3
              value: bar3
            - name: FOO4
              value: bar4
            - name: FOO5
              value: bar5
          resources:
            requests:
              cpu: 100m
