apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dummy-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{ .name }}-dummy-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/omegion/argocd-test-repo
        targetRevision: HEAD
        path: apps/dummy-app
      destination:
        server: '{{ .server }}'
        namespace: dummy-app
      ignoreDifferences:
        - group: "*"
          kind: "Deployment"
          jqPathExpressions:
            - '.spec.template.spec.containers[] | select(.name == "nginx") | .image'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
#          - RespectIgnoreDifferences=true